export const NIGERIAN_UNIVERSITIES = [
  "University of Lagos (UNILAG)",
  "University of Ibadan (UI)",
  "Obafemi Awolowo University (OAU)",
  "University of Nigeria, Nsukka (UNN)",
  "Ahmadu Bello University (ABU)",
  "University of Benin (UNIBEN)",
  "Federal University of Technology, Akure (FUTA)",
  "University of Ilorin (UNILORIN)",
  "Bayero University, Kano (BUK)",
  "University of Jos (UNIJOS)",
  "University of Abuja (UNIABUJA)",
  "Lagos State University (LASU)",
  "Covenant University",
  "Babcock University",
  "Pan-Atlantic University (PAU)",
  "Redeemer's University",
  "Landmark University",
  "American University of Nigeria (AUN)",
  "Bowen University",
  "Crawford University",
  "Federal University, Oye-Ekiti (FUOYE)",
  "Federal University, Lafia (FULAFIA)",
  "Federal University, Lokoja (FULOKOJA)",
  "Federal University, Kashere (FUKASHERE)",
  "Nnamdi Azikiwe University (UNIZIK)",
  "Enugu State University of Science and Technology (ESUT)",
  "Imo State University (IMSU)",
  "Rivers State University (RSU)",
  "Delta State University (DELSU)",
  "Kwara State University (KWASU)",
  "Kogi State University (KSU)",
  "Benue State University (BSU)",
  "Cross River University of Technology (CRUTECH)",
  "Akwa Ibom State University (AKSU)",
  "Ekiti State University (EKSU)",
  "Osun State University (UNIOSUN)",
  "Ondo State University of Science and Technology (OSUSTECH)",
  "Tai Solarin University of Education (TASUED)",
  "Federal University of Agriculture, Abeokuta (FUNAAB)",
  "Michael Okpara University of Agriculture (MOUAU)",
  "University of Agriculture, Makurdi (UAM)",
  "Federal University of Petroleum Resources, Effurun (FUPRE)",
  "Abubakar Tafawa Balewa University (ATBU)",
  "Federal University of Technology, Minna (FUTMINNA)",
  "Federal University of Technology, Owerri (FUTO)",
  "Modibbo Adama University, Yola (MAUTECH)",
  "Ibrahim Badamasi Babangida University (IBBU)",
  "Niger Delta University (NDU)",
  "Ignatius Ajuru University of Education (IAUE)",
  "Olabisi Onabanjo University (OOU)",
];

// Alias for backward compatibility
export const UNIVERSITIES = NIGERIAN_UNIVERSITIES;
