/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const TicketEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'availableTickets' : IDL.Nat,
  'verifiers' : IDL.Vec(IDL.Principal),
  'description' : IDL.Text,
  'university' : IDL.Text,
  'ticketPrice' : IDL.Nat,
  'eventDate' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaAttachment = IDL.Variant({
  'video' : ExternalBlob,
  'image' : ExternalBlob,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'university' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'media' : IDL.Opt(MediaAttachment),
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
  'university' : IDL.Text,
  'timestamp' : Time,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'parentComment' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
  'postId' : IDL.Nat,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'participants' : IDL.Vec(IDL.Principal),
  'lastMessageTime' : Time,
});
export const Ticket = IDL.Record({
  'eventId' : IDL.Nat,
  'code' : IDL.Text,
  'attendee' : IDL.Principal,
  'checkedIn' : IDL.Bool,
  'pricePaid' : IDL.Nat,
  'checkedInAt' : IDL.Opt(Time),
});
export const MarketplaceListing = IDL.Record({
  'id' : IDL.Nat,
  'media' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'sold' : IDL.Bool,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'university' : IDL.Text,
  'timestamp' : Time,
  'price' : IDL.Nat,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'conversationId' : IDL.Nat,
  'timestamp' : Time,
});
export const NotificationType = IDL.Variant({
  'like' : IDL.Null,
  'comment' : IDL.Null,
  'message' : IDL.Null,
  'follow' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notificationType' : NotificationType,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
  'timestamp' : Time,
  'relatedId' : IDL.Opt(IDL.Nat),
  'relatedUser' : IDL.Opt(IDL.Principal),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'browseTicketEvents' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
      [IDL.Vec(TicketEvent)],
      ['query'],
    ),
  'checkInTicket' : IDL.Func([IDL.Text], [], []),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(MediaAttachment)], [IDL.Nat], []),
  'createTicketEvent' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Vec(IDL.Principal), IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampusFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getCommentThread' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Vec(Comment)],
      ['query'],
    ),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getContactList' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getEventTickets' : IDL.Func([IDL.Nat], [IDL.Vec(Ticket)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowingFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(MarketplaceListing)], ['query']),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getMyTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'getNotifications' : IDL.Func(
      [IDL.Opt(Time)],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getTicketEvent' : IDL.Func([IDL.Nat], [IDL.Opt(TicketEvent)], ['query']),
  'getUniversalFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
  'hasProfile' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'issueTicket' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Text], [], []),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'listConversations' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Conversation)],
      ['query'],
    ),
  'listMarketplaceListings' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(MarketplaceListing)],
      ['query'],
    ),
  'listPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'listTicketEvents' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(TicketEvent)],
      ['query'],
    ),
  'markListingAsSold' : IDL.Func([IDL.Nat], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'purchaseTicket' : IDL.Func([IDL.Nat], [], []),
  'revokeAdminRole' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListings' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(MarketplaceListing)],
      ['query'],
    ),
  'searchUsers' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'startConversation' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'verifyTicket' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const TicketEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'availableTickets' : IDL.Nat,
    'verifiers' : IDL.Vec(IDL.Principal),
    'description' : IDL.Text,
    'university' : IDL.Text,
    'ticketPrice' : IDL.Nat,
    'eventDate' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaAttachment = IDL.Variant({
    'video' : ExternalBlob,
    'image' : ExternalBlob,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'university' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'media' : IDL.Opt(MediaAttachment),
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
    'university' : IDL.Text,
    'timestamp' : Time,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'parentComment' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
    'postId' : IDL.Nat,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'participants' : IDL.Vec(IDL.Principal),
    'lastMessageTime' : Time,
  });
  const Ticket = IDL.Record({
    'eventId' : IDL.Nat,
    'code' : IDL.Text,
    'attendee' : IDL.Principal,
    'checkedIn' : IDL.Bool,
    'pricePaid' : IDL.Nat,
    'checkedInAt' : IDL.Opt(Time),
  });
  const MarketplaceListing = IDL.Record({
    'id' : IDL.Nat,
    'media' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'sold' : IDL.Bool,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'university' : IDL.Text,
    'timestamp' : Time,
    'price' : IDL.Nat,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'conversationId' : IDL.Nat,
    'timestamp' : Time,
  });
  const NotificationType = IDL.Variant({
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'message' : IDL.Null,
    'follow' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notificationType' : NotificationType,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
    'timestamp' : Time,
    'relatedId' : IDL.Opt(IDL.Nat),
    'relatedUser' : IDL.Opt(IDL.Principal),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'browseTicketEvents' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
        [IDL.Vec(TicketEvent)],
        ['query'],
      ),
    'checkInTicket' : IDL.Func([IDL.Text], [], []),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Opt(MediaAttachment)],
        [IDL.Nat],
        [],
      ),
    'createTicketEvent' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Vec(IDL.Principal), IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampusFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getCommentThread' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getContactList' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getEventTickets' : IDL.Func([IDL.Nat], [IDL.Vec(Ticket)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowingFeed' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getListing' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MarketplaceListing)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getMyTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Opt(Time)],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getTicketEvent' : IDL.Func([IDL.Nat], [IDL.Opt(TicketEvent)], ['query']),
    'getUniversalFeed' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
    'hasProfile' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'issueTicket' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Text], [], []),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'listConversations' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Conversation)],
        ['query'],
      ),
    'listMarketplaceListings' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(MarketplaceListing)],
        ['query'],
      ),
    'listPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'listTicketEvents' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(TicketEvent)],
        ['query'],
      ),
    'markListingAsSold' : IDL.Func([IDL.Nat], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'purchaseTicket' : IDL.Func([IDL.Nat], [], []),
    'revokeAdminRole' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListings' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(MarketplaceListing)],
        ['query'],
      ),
    'searchUsers' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'startConversation' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'verifyTicket' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };