/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'parentComment' : [] | [bigint],
  'timestamp' : Time,
  'postId' : bigint,
}
export interface Conversation {
  'id' : bigint,
  'participants' : Array<Principal>,
  'lastMessageTime' : Time,
}
export type ExternalBlob = Uint8Array;
export interface MarketplaceListing {
  'id' : bigint,
  'media' : [] | [ExternalBlob],
  'title' : string,
  'sold' : boolean,
  'description' : string,
  'seller' : Principal,
  'university' : string,
  'timestamp' : Time,
  'price' : bigint,
}
export type MediaAttachment = { 'video' : ExternalBlob } |
  { 'image' : ExternalBlob };
export interface Message {
  'id' : bigint,
  'content' : string,
  'sender' : Principal,
  'conversationId' : bigint,
  'timestamp' : Time,
}
export interface Notification {
  'id' : bigint,
  'notificationType' : NotificationType,
  'read' : boolean,
  'recipient' : Principal,
  'timestamp' : Time,
  'relatedId' : [] | [bigint],
  'relatedUser' : [] | [Principal],
}
export type NotificationType = { 'like' : null } |
  { 'comment' : null } |
  { 'message' : null } |
  { 'follow' : null };
export interface Post {
  'id' : bigint,
  'media' : [] | [MediaAttachment],
  'content' : string,
  'author' : Principal,
  'likes' : bigint,
  'university' : string,
  'timestamp' : Time,
}
export interface Ticket {
  'eventId' : bigint,
  'code' : string,
  'attendee' : Principal,
  'checkedIn' : boolean,
  'pricePaid' : bigint,
  'checkedInAt' : [] | [Time],
}
export interface TicketEvent {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'availableTickets' : bigint,
  'verifiers' : Array<Principal>,
  'description' : string,
  'university' : string,
  'ticketPrice' : bigint,
  'eventDate' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'university' : string,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, [] | [bigint]], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'browseTicketEvents' : ActorMethod<
    [[] | [string], bigint, bigint],
    Array<TicketEvent>
  >,
  'checkInTicket' : ActorMethod<[string], undefined>,
  'createListing' : ActorMethod<
    [string, string, bigint, [] | [ExternalBlob]],
    bigint
  >,
  'createPost' : ActorMethod<[string, [] | [MediaAttachment]], bigint>,
  'createTicketEvent' : ActorMethod<
    [string, string, Time, Array<Principal>, bigint, bigint],
    bigint
  >,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampusFeed' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getCommentThread' : ActorMethod<[bigint, [] | [bigint]], Array<Comment>>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getContactList' : ActorMethod<[], Array<Conversation>>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getEventTickets' : ActorMethod<[bigint], Array<Ticket>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowingFeed' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getListing' : ActorMethod<[bigint], [] | [MarketplaceListing]>,
  'getMessages' : ActorMethod<[bigint], Array<Message>>,
  'getMyTickets' : ActorMethod<[], Array<Ticket>>,
  'getNotifications' : ActorMethod<[[] | [Time]], Array<Notification>>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getTicketEvent' : ActorMethod<[bigint], [] | [TicketEvent]>,
  'getUniversalFeed' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdminRole' : ActorMethod<[Principal], undefined>,
  'hasProfile' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'issueTicket' : ActorMethod<[bigint, Principal, string], undefined>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'listAdmins' : ActorMethod<[], Array<Principal>>,
  'listConversations' : ActorMethod<[bigint, bigint], Array<Conversation>>,
  'listMarketplaceListings' : ActorMethod<
    [bigint, bigint],
    Array<MarketplaceListing>
  >,
  'listPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'listTicketEvents' : ActorMethod<[bigint, bigint], Array<TicketEvent>>,
  'markListingAsSold' : ActorMethod<[bigint], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'purchaseTicket' : ActorMethod<[bigint], undefined>,
  'revokeAdminRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListings' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<MarketplaceListing>
  >,
  'searchUsers' : ActorMethod<[string, [] | [string]], Array<UserProfile>>,
  'sendMessage' : ActorMethod<[bigint, string], bigint>,
  'startConversation' : ActorMethod<[Principal], bigint>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'verifyTicket' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];