/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TicketEvent {
    id: bigint;
    title: string;
    creator: Principal;
    availableTickets: bigint;
    verifiers: Array<Principal>;
    description: string;
    university: string;
    ticketPrice: bigint;
    eventDate: Time;
}
export type Time = bigint;
export interface Comment {
    id: bigint;
    content: string;
    author: Principal;
    parentComment?: bigint;
    timestamp: Time;
    postId: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type MediaAttachment = {
    __kind__: "video";
    video: ExternalBlob;
} | {
    __kind__: "image";
    image: ExternalBlob;
};
export interface MarketplaceListing {
    id: bigint;
    media?: ExternalBlob;
    title: string;
    sold: boolean;
    description: string;
    seller: Principal;
    university: string;
    timestamp: Time;
    price: bigint;
}
export interface Post {
    id: bigint;
    media?: MediaAttachment;
    content: string;
    author: Principal;
    likes: bigint;
    university: string;
    timestamp: Time;
}
export interface Notification {
    id: bigint;
    notificationType: NotificationType;
    read: boolean;
    recipient: Principal;
    timestamp: Time;
    relatedId?: bigint;
    relatedUser?: Principal;
}
export interface Message {
    id: bigint;
    content: string;
    sender: Principal;
    conversationId: bigint;
    timestamp: Time;
}
export interface Ticket {
    eventId: bigint;
    code: string;
    attendee: Principal;
    checkedIn: boolean;
    pricePaid: bigint;
    checkedInAt?: Time;
}
export interface Conversation {
    id: bigint;
    participants: Array<Principal>;
    lastMessageTime: Time;
}
export interface UserProfile {
    bio: string;
    username: string;
    displayName: string;
    university: string;
    avatar?: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum NotificationType {
    like = "like",
    comment = "comment",
    message = "message",
    follow = "follow"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(postId: bigint, content: string, parentComment: bigint | null): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    browseTicketEvents(universityFilter: string | null, limit: bigint, offset: bigint): Promise<Array<TicketEvent>>;
    checkInTicket(code: string): Promise<void>;
    createListing(title: string, description: string, price: bigint, media: ExternalBlob | null): Promise<bigint>;
    createPost(content: string, media: MediaAttachment | null): Promise<bigint>;
    createTicketEvent(title: string, description: string, eventDate: Time, verifiers: Array<Principal>, ticketPrice: bigint, availableTickets: bigint): Promise<bigint>;
    deleteComment(commentId: bigint): Promise<void>;
    deleteListing(listingId: bigint): Promise<void>;
    deletePost(postId: bigint): Promise<void>;
    followUser(user: Principal): Promise<void>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCampusFeed(limit: bigint, offset: bigint): Promise<Array<Post>>;
    getCommentThread(postId: bigint, parentComment: bigint | null): Promise<Array<Comment>>;
    getComments(postId: bigint): Promise<Array<Comment>>;
    getContactList(): Promise<Array<Conversation>>;
    getConversations(): Promise<Array<Conversation>>;
    getEventTickets(eventId: bigint): Promise<Array<Ticket>>;
    getFollowers(user: Principal): Promise<Array<Principal>>;
    getFollowing(user: Principal): Promise<Array<Principal>>;
    getFollowingFeed(limit: bigint, offset: bigint): Promise<Array<Post>>;
    getListing(listingId: bigint): Promise<MarketplaceListing | null>;
    getMessages(conversationId: bigint): Promise<Array<Message>>;
    getMyTickets(): Promise<Array<Ticket>>;
    getNotifications(since: Time | null): Promise<Array<Notification>>;
    getPost(postId: bigint): Promise<Post | null>;
    getTicketEvent(eventId: bigint): Promise<TicketEvent | null>;
    getUniversalFeed(limit: bigint, offset: bigint): Promise<Array<Post>>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantAdminRole(user: Principal): Promise<void>;
    hasProfile(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isFollowing(user: Principal): Promise<boolean>;
    issueTicket(eventId: bigint, attendee: Principal, code: string): Promise<void>;
    likePost(postId: bigint): Promise<void>;
    listAdmins(): Promise<Array<Principal>>;
    listConversations(limit: bigint, offset: bigint): Promise<Array<Conversation>>;
    listMarketplaceListings(limit: bigint, offset: bigint): Promise<Array<MarketplaceListing>>;
    listPosts(limit: bigint, offset: bigint): Promise<Array<Post>>;
    listTicketEvents(limit: bigint, offset: bigint): Promise<Array<TicketEvent>>;
    markListingAsSold(listingId: bigint): Promise<void>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    purchaseTicket(eventId: bigint): Promise<void>;
    revokeAdminRole(user: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchListings(searchTerm: string | null, universityFilter: string | null): Promise<Array<MarketplaceListing>>;
    searchUsers(term: string, universityFilter: string | null): Promise<Array<UserProfile>>;
    sendMessage(conversationId: bigint, content: string): Promise<bigint>;
    startConversation(otherUser: Principal): Promise<bigint>;
    unfollowUser(user: Principal): Promise<void>;
    unlikePost(postId: bigint): Promise<void>;
    verifyTicket(code: string): Promise<boolean>;
}
import type { Comment as _Comment, ExternalBlob as _ExternalBlob, MarketplaceListing as _MarketplaceListing, MediaAttachment as _MediaAttachment, Notification as _Notification, NotificationType as _NotificationType, Post as _Post, Ticket as _Ticket, TicketEvent as _TicketEvent, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string, arg2: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async browseTicketEvents(arg0: string | null, arg1: bigint, arg2: bigint): Promise<Array<TicketEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseTicketEvents(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseTicketEvents(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async checkInTicket(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkInTicket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkInTicket(arg0);
            return result;
        }
    }
    async createListing(arg0: string, arg1: string, arg2: bigint, arg3: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createPost(arg0: string, arg1: MediaAttachment | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTicketEvent(arg0: string, arg1: string, arg2: Time, arg3: Array<Principal>, arg4: bigint, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTicketEvent(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTicketEvent(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCampusFeed(arg0: bigint, arg1: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampusFeed(arg0, arg1);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampusFeed(arg0, arg1);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommentThread(arg0: bigint, arg1: bigint | null): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentThread(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentThread(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactList(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactList();
            return result;
        }
    }
    async getConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return result;
        }
    }
    async getEventTickets(arg0: bigint): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventTickets(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventTickets(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFollowing(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0);
            return result;
        }
    }
    async getFollowingFeed(arg0: bigint, arg1: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowingFeed(arg0, arg1);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowingFeed(arg0, arg1);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: bigint): Promise<MarketplaceListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMyTickets(): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTickets();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTickets();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: Time | null): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(to_candid_opt_n41(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(to_candid_opt_n41(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: bigint): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicketEvent(arg0: bigint): Promise<TicketEvent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicketEvent(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicketEvent(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUniversalFeed(arg0: bigint, arg1: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniversalFeed(arg0, arg1);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniversalFeed(arg0, arg1);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantAdminRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantAdminRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantAdminRole(arg0);
            return result;
        }
    }
    async hasProfile(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasProfile();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFollowing(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0);
            return result;
        }
    }
    async issueTicket(arg0: bigint, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.issueTicket(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.issueTicket(arg0, arg1, arg2);
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async listAdmins(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAdmins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAdmins();
            return result;
        }
    }
    async listConversations(arg0: bigint, arg1: bigint): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConversations(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConversations(arg0, arg1);
            return result;
        }
    }
    async listMarketplaceListings(arg0: bigint, arg1: bigint): Promise<Array<MarketplaceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMarketplaceListings(arg0, arg1);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMarketplaceListings(arg0, arg1);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPosts(arg0: bigint, arg1: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPosts(arg0, arg1);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPosts(arg0, arg1);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTicketEvents(arg0: bigint, arg1: bigint): Promise<Array<TicketEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTicketEvents(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTicketEvents(arg0, arg1);
            return result;
        }
    }
    async markListingAsSold(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markListingAsSold(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markListingAsSold(arg0);
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async purchaseTicket(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseTicket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseTicket(arg0);
            return result;
        }
    }
    async revokeAdminRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeAdminRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeAdminRole(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchListings(arg0: string | null, arg1: string | null): Promise<Array<MarketplaceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListings(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListings(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchUsers(arg0: string, arg1: string | null): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async startConversation(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.startConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startConversation(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unlikePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async verifyTicket(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyTicket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyTicket(arg0);
            return result;
        }
    }
}
function from_candid_Comment_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Comment): Comment {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_MarketplaceListing_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketplaceListing): Promise<MarketplaceListing> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_MediaAttachment_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaAttachment): Promise<MediaAttachment> {
    return await from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_Post_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Ticket_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ticket): Ticket {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MediaAttachment]): Promise<MediaAttachment | null> {
    return value.length === 0 ? null : await from_candid_MediaAttachment_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketplaceListing]): Promise<MarketplaceListing | null> {
    return value.length === 0 ? null : await from_candid_MarketplaceListing_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Promise<Post | null> {
    return value.length === 0 ? null : await from_candid_Post_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TicketEvent]): TicketEvent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    displayName: string;
    university: string;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    bio: string;
    username: string;
    displayName: string;
    university: string;
    avatar?: ExternalBlob;
}> {
    return {
        bio: value.bio,
        username: value.username,
        displayName: value.displayName,
        university: value.university,
        avatar: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    media: [] | [_MediaAttachment];
    content: string;
    author: Principal;
    likes: bigint;
    university: string;
    timestamp: _Time;
}): Promise<{
    id: bigint;
    media?: MediaAttachment;
    content: string;
    author: Principal;
    likes: bigint;
    university: string;
    timestamp: Time;
}> {
    return {
        id: value.id,
        media: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.media)),
        content: value.content,
        author: value.author,
        likes: value.likes,
        university: value.university,
        timestamp: value.timestamp
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    author: Principal;
    parentComment: [] | [bigint];
    timestamp: _Time;
    postId: bigint;
}): {
    id: bigint;
    content: string;
    author: Principal;
    parentComment?: bigint;
    timestamp: Time;
    postId: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        author: value.author,
        parentComment: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.parentComment)),
        timestamp: value.timestamp,
        postId: value.postId
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eventId: bigint;
    code: string;
    attendee: Principal;
    checkedIn: boolean;
    pricePaid: bigint;
    checkedInAt: [] | [_Time];
}): {
    eventId: bigint;
    code: string;
    attendee: Principal;
    checkedIn: boolean;
    pricePaid: bigint;
    checkedInAt?: Time;
} {
    return {
        eventId: value.eventId,
        code: value.code,
        attendee: value.attendee,
        checkedIn: value.checkedIn,
        pricePaid: value.pricePaid,
        checkedInAt: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.checkedInAt))
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    media: [] | [_ExternalBlob];
    title: string;
    sold: boolean;
    description: string;
    seller: Principal;
    university: string;
    timestamp: _Time;
    price: bigint;
}): Promise<{
    id: bigint;
    media?: ExternalBlob;
    title: string;
    sold: boolean;
    description: string;
    seller: Principal;
    university: string;
    timestamp: Time;
    price: bigint;
}> {
    return {
        id: value.id,
        media: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.media)),
        title: value.title,
        sold: value.sold,
        description: value.description,
        seller: value.seller,
        university: value.university,
        timestamp: value.timestamp,
        price: value.price
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    notificationType: _NotificationType;
    read: boolean;
    recipient: Principal;
    timestamp: _Time;
    relatedId: [] | [bigint];
    relatedUser: [] | [Principal];
}): {
    id: bigint;
    notificationType: NotificationType;
    read: boolean;
    recipient: Principal;
    timestamp: Time;
    relatedId?: bigint;
    relatedUser?: Principal;
} {
    return {
        id: value.id,
        notificationType: from_candid_NotificationType_n45(_uploadFile, _downloadFile, value.notificationType),
        read: value.read,
        recipient: value.recipient,
        timestamp: value.timestamp,
        relatedId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.relatedId)),
        relatedUser: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.relatedUser))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: _ExternalBlob;
} | {
    image: _ExternalBlob;
}): Promise<{
    __kind__: "video";
    video: ExternalBlob;
} | {
    __kind__: "image";
    image: ExternalBlob;
}> {
    return "video" in value ? {
        __kind__: "video",
        video: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.video)
    } : "image" in value ? {
        __kind__: "image",
        image: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.image)
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    like: null;
} | {
    comment: null;
} | {
    message: null;
} | {
    follow: null;
}): NotificationType {
    return "like" in value ? NotificationType.like : "comment" in value ? NotificationType.comment : "message" in value ? NotificationType.message : "follow" in value ? NotificationType.follow : value;
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Promise<Array<Post>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Post_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Comment>): Array<Comment> {
    return value.map((x)=>from_candid_Comment_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ticket>): Array<Ticket> {
    return value.map((x)=>from_candid_Ticket_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n43(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketplaceListing>): Promise<Array<MarketplaceListing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MarketplaceListing_n39(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_MediaAttachment_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaAttachment): Promise<_MediaAttachment> {
    return await to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaAttachment | null): Promise<[] | [_MediaAttachment]> {
    return value === null ? candid_none() : candid_some(await to_candid_MediaAttachment_n15(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    displayName: string;
    university: string;
    avatar?: ExternalBlob;
}): Promise<{
    bio: string;
    username: string;
    displayName: string;
    university: string;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio,
        username: value.username,
        displayName: value.displayName,
        university: value.university,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "video";
    video: ExternalBlob;
} | {
    __kind__: "image";
    image: ExternalBlob;
}): Promise<{
    video: _ExternalBlob;
} | {
    image: _ExternalBlob;
}> {
    return value.__kind__ === "video" ? {
        video: await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.video)
    } : value.__kind__ === "image" ? {
        image: await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.image)
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
